enum AppDispatchType {
  'ERROR' = 'SET_APP_ERROR',
  'PALETTE' = 'SET_APP_PALETTE',
  'LANG' = 'SET_APP_LANG',
}

enum CreateProjectDispatchType {
  'FILTERED_MEMS' = 'SET_CREATE_PROJ_FILTERED_MEMBERS',
}

enum ListProjectDispatchType {
  'PAGE' = 'SET_PROJECT_LIST_PAGE',
  'LIMIT' = 'SET_PROJECT_LIST_LIMIT',
  'ADVANCED' = 'SET_PROJECT_LIST_ADVANCED',
  'STATUS' = 'SET_PROJECT_LIST_STATUS',
  'KEYWORD' = 'SET_PROJECT_LIST_KEYWORD',
  'START_DATE' = 'SET_PROJECT_LIST_START_DATE',
  'END_DATE' = 'SET_PROJECT_LIST_END_DATE',
  'CONTAIN_MEMBERS' = 'SET_PROJECT_LIST_CONTAIN_MEMBERS',
  'FILTERED_MEMBERS' = 'SET_PROJECT_LIST_FILTERED_MEMBERS',
}

export const DispatchType = {
  APP: AppDispatchType,
  CREATE_PROJ: CreateProjectDispatchType,
  LIST_PROJ: ListProjectDispatchType,
};
